### PR TITLE
Added call for ES Update API

### PR DESCRIPTION
**Pull request by marcust**
Based on 1.3.0 Branch

### CODE REVIEW

**Comment by adrianluisgonzalez** [comment]
Thanks for the PR.  

I'm not sure what to do with some of the changes though, especially in the POM (changed groupId, parent pom, and added dependencies) and the change to JDK 8 with lambdas.  I'm guessing you have just built your own version since you have changed the groupId.

The develop branch is for vert.x 3 (and JDK 8).  Any chance you would resubmit for vert.x 3?

**Comment by marcust** [comment]
So there are no Vert.x 2 compatible Versions planned anymore? If not so I would create a new PR without the POM changes.

I guess we will migrate to vert.x 3 someday, so there is a chance I will resubmit.

**Comment by adrianluisgonzalez** [comment]
I hadn't planned on any further vert.x 2.x development, but if it would help I can do a 1.4 build with update and fetch source.

**Comment by marcust** [comment]
Well, I just want to contrubute back what I build. Maybe someone else needs that as well. How do we do it then? Do you want to create a 1.x branch I can rebase against?

**Pull request closed without merging**
